FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake bison flex mysql-server libz-dev

COPY . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8
